### ISSUE TITLE
Direct Messages?

### ISSUE THREAD

**Issue by manavortex** [sm00th/bitlbee-discord#64]
Hey, 
my husband says there is some sort of central discord network where you are supposed to be able to talk to everyone without them being on the same server. It's called "Direct Messages", I think. What do I have to do for that to work?
I did get messages from someone who was on the same server as I was, but not serverwide.

thanks!

**Comment by sm00th** [comment]
You can't add new people through bitlbee-discord that are not in the same "guilds"/"servers" as you are, but once you add a person through standard discord client you should be able to send/receive messages to those people. I haven't tested this though, so if you don't receive such messages there might be more to it than I thought.

**Comment by manavortex** [comment]
Nope - we did that and it didn't work.
I appreciate your work on this! If you need anything, get in touch.

**Comment by JiK** [comment]
I have a friend with whom I'm not in the same server. Apparently I can talk to him via Bitlbee when he is online but there's no way to reach him when he is offline. These show as "Direct Messages" in the Discord browser app, so I guess this is the right place to report this.

I have `show_users = `online+,special,away,offline'` set but I don't see him in the control channel list at the moment. I get `User does not exist: <nick>` when I try to talk to him in the control channel and my client reports `No such nick/channel` if I try to talk to him in query.

But I have been able to talk to him via bitlbee when he is responding to me. Looking at my logs, it seems that last time bitlbee didn't get his first message at all, but bitlbee started working from his second message to me. Unfortunately I can't create a proper bug report now because I have only one friend (:D) and I don't want to bother him too much about this. But I guess this might have something to do with offline/online status.

**Comment by sm00th** [comment]
Fixed on `listchan` branch, but I'll keep this issue open for a while to make sure everything works for you. At this point I am not going to backport it to master as listchan will be soon merged.

**Comment by JiK** [comment]
I cherry-picked the commit you linked, and now I don't see the friends at all, even during an ongoing discussion. Should I try the full listchan branch instead? I couldn't get the listchan branch to compile because it apparently needs a newer version of bitlbee header files than I have installed, but I guess I'll have to update bitlbee to the newest git version also?

**Comment by sm00th** [comment]
Yes, I wouldn't expect this to work on master by just cherrypicking it onto it, listchan should work for you.
If you are using a debian-based system you can get newer bitlbee version from official repos: http://code.bitlbee.org/debian/, otherwise you'll have to compile it from git or wait a bit till the new release (should be soon), I'll be merging listchan branch to master after the release.

**Comment by JiK** [comment]
I'm now running `BitlBee-LIBPURPLE 3.4.2+20170103+master+115-g3b8e4be-git` with the latest listchan branch of bitlbee-discord, but I still don't see friends unless there is an ongoing discussion.

**Comment by sm00th** [comment]
Indeed it doesn't work the way it is now. I have a patch that fixes this for good, but I'm currently postponing it till the listchan merge into master, sorry. I hope I'll be able to deliver next week, I at least want archlinux to update it's bitlbee package to 3.5 before proceeding.

**Comment by sm00th** [comment]
Oh wow, github now autocloses issues.

This should be properly fixed on latest master now, can you try it out?

**Comment by manavortex** [comment]
Will give it a try.

**Comment by JiK** [comment]
Seems to work now for me (with the latest version of bitlbee), thank you!

**Comment by sm00th** [comment]
I assume it works now, so closing the issue. Please reopen if you find something odd with this feature.
